### ISSUE TITLE
Multiple S3 ops

### ISSUE THREAD

**Issue by Enchufa2** [wch/s3ops#1]
I landed here from [here](https://github.com/wch/R6/issues/44) because I was trying to do exactly that. But it's true it's much better to avoid S4. So I tried this:

``` r
library(R6)

dummy <- R6Class("dummy",
  public = list(
    v = NA,
    initialize = function(v) {
      self$v <- v
    }
  )
)

`+.dummy` <- function(e1, e2) { e1$v + e2$v }

a <- dummy$new(1)
b <- dummy$new(2)

a + b
#> 3
```

And everything works as expected. But then I tried the following:

``` r
a + b + a
#> Error in e1$v : $ operator is invalid for atomic vectors
```

So I would like to understand what's happening here and whether would be possible to add up any number of objects.

**Comment by wch** [comment]
That's because `a + b + a` is equivalent to `(a + b) + a`. That becomes `3 + a`. If you run `3 + a`, you'll get the same error.

**Comment by Enchufa2** [comment]
So true. Stupid question. :smile: Thank you.

**Comment by Enchufa2** [comment]
Just for the sake of completeness, if anyone reaches this issue, a complete working example of what I was actually trying to do:

``` r
library(R6)

dummy <- R6Class("dummy",
  public = list(
    v = NA,
    initialize = function(v) {
      self$v <- v
    },
    print = function() print(self$v)
  )
)

`+.dummy` <- function(e1, e2) { dummy$new(e1$v + e2$v) }

a <- dummy$new(1)
b <- dummy$new(2)

a + b + a
#> 4
```

**Comment by wch** [comment]
No worries, thanks for the follow-up example. :)
